// SYNCED FROM ../../lead-audit-tool/src/reporting.mjs — do not edit here.
// Re-sync with: node lead-audit-tool/scripts/sync-shared.mjs

// IC Business Systems audit — reporting / formatting layer.
//
// Two exports drive every downstream consumer (public audit.js, internal tool,
// future CLI). DO NOT bypass these and template strings in the UI layer —
// drift kills the test contract.

export const ENGINE_VERSION = "0.1.0";

function escapeCell(value) {
  if (value === null || value === undefined) return "—";
  const str = String(value).trim();
  if (str === "") return "—";
  const capped = str.length > 200 ? str.slice(0, 200) : str;
  return capped
    .replace(/\|/g, "\\|")
    .replace(/`/g, "'")
    .replace(/\r?\n/g, " ");
}

function indentCodeBlock(value) {
  const str = value === null || value === undefined ? "" : String(value);
  return str
    .split(/\r?\n/)
    .map((line) => "    " + line)
    .join("\n");
}

function footerLine() {
  return `--- Generated by IC Business Systems audit v${ENGINE_VERSION} — ${new Date().toISOString()}`;
}

export function formatScorecard(audit) {
  const {
    businessName,
    websiteUrl,
    score,
    contactPriority,
    summary,
    topLeak,
    findings = [],
    outreachMessage
  } = audit;

  const lines = [];
  lines.push(`${businessName} — ${websiteUrl}`);
  lines.push(`Score: ${score}/100   Priority: ${contactPriority}`);
  lines.push(summary);
  lines.push("");

  if (topLeak) {
    lines.push(`Top leak: ${topLeak.issue}`);
    if (topLeak.fix) lines.push(`Fix: ${topLeak.fix}`);
  } else {
    lines.push("Top leak: none — core lead path is solid.");
  }
  lines.push("");

  lines.push("Findings:");
  for (const finding of findings) {
    lines.push(`  ${finding.label} [${finding.status}] — ${finding.issue}`);
  }
  lines.push("");

  if (outreachMessage) {
    lines.push("Outreach message:");
    lines.push(outreachMessage);
    lines.push("");
  }

  lines.push(footerLine());
  return lines.join("\n");
}

export function formatCrmExport(audit) {
  const {
    businessName,
    websiteUrl,
    niche,
    notes,
    score,
    contactPriority,
    topLeak,
    outreachMessage
  } = audit;

  const lines = [];
  lines.push("| Field | Value |");
  lines.push("|---|---|");
  lines.push(`| Business | ${escapeCell(businessName)} |`);
  lines.push(`| URL | ${escapeCell(websiteUrl)} |`);
  lines.push(`| Niche | ${escapeCell(niche)} |`);
  lines.push(`| Score | ${score}/100 |`);
  lines.push(`| Priority | ${contactPriority} |`);
  lines.push(`| Top leak | ${escapeCell(topLeak ? topLeak.issue : "none")} |`);
  lines.push(`| Notes | ${escapeCell(notes)} |`);
  lines.push("");
  lines.push("**Outreach message:**");
  lines.push("");
  lines.push(indentCodeBlock(outreachMessage ?? ""));
  lines.push("");
  lines.push(footerLine());
  return lines.join("\n");
}
